DATABASE:
  HOST: "localhost"
  DATABASE: "darkweb_markets_forums1"
  USER: "postgres"
  PASSWORD: "#arshly4P"

FORUM:
  ID: "2"
  POST_THRESHOLD: "0"

NETWORK:
  USER_POSTS_THRESHOLD: "1"
  USER_THREADS_THRESHOLD: "1"
  THREAD_POSTS_THRESHOLD: "1"
  THREAD_USERS_THRESHOLD: "1"

TAO:
  SUSCEPTIBLE: "8760"  # Number of hours
  FORGETTABLE: "8760"  # Number of hours

FEATURE:
  NAN: "True"
  PNE: "True"
  HUB: "False"

DATE:
  BEGIN: "2000-06-01"
  END: "2020-10-31"

HYPERPARAMS_ET:
  N_ESTIMATORS: "100"
  sqrt: "auto"
  MIN_SAMPLES_SPLIT: "2"

